<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260208163111 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE country_mapping (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_name VARCHAR(255) NOT NULL, external_code VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, match INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tour_operator_id INT NOT NULL, country_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_80AA74E73813CA60 ON country_mapping (tour_operator_id)');
        $this->addSql('CREATE INDEX IDX_80AA74E7F92F3E70 ON country_mapping (country_id)');
        $this->addSql('ALTER TABLE country_mapping ADD CONSTRAINT FK_80AA74E73813CA60 FOREIGN KEY (tour_operator_id) REFERENCES tour_operator (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE country_mapping ADD CONSTRAINT FK_80AA74E7F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE country_mapping DROP CONSTRAINT FK_80AA74E73813CA60');
        $this->addSql('ALTER TABLE country_mapping DROP CONSTRAINT FK_80AA74E7F92F3E70');
        $this->addSql('DROP TABLE country_mapping');
    }
}
